# Support for Docker Compose v2, https://docs.docker.com/compose/overview/
version: '2'
services:

  client:
    hostname: client
    depends_on:
      - controller
    build: ./build/client
    environment:
      - CLIENT_ID=1
    volumes:
      - ./data/client:/data/client
    ports:
      - "22:22"
  
  controller:
    hostname: controller
    build: ./build/controller
    volumes:
      - ./data/controller:/data/controller

networks:
  default:

